### ISSUE TITLE
User segmentation batch jobs

### ISSUE THREAD

**Issue by james-jory** [aws-solutions/maintaining-personalized-experiences-with-machine-learning#11]
**Describe the feature you'd like**
Add support for the new user segmentation batch jobs to the solution.

https://docs.aws.amazon.com/en_us/personalize/latest/dg/user-segmentation-recipes.html

**Additional context**
https://aws.amazon.com/about-aws/whats-new/2021/11/amazon-personalize-intelligent-user-segmentation/

**Comment by pwrmiller** [comment]
Resolved in v1.2.0!
