### ISSUE TITLE
Domain dataset groups and recommenders

### ISSUE THREAD

**Issue by james-jory** [aws-solutions/maintaining-personalized-experiences-with-machine-learning#12]
**Describe the feature you'd like**
Add support for the new domain dataset groups and recommenders.

https://docs.aws.amazon.com/personalize/latest/dg/domain-dataset-groups.html

**Additional context**
https://aws.amazon.com/blogs/machine-learning/amazon-personalize-announces-recommenders-optimized-for-retail-and-media-entertainment/

**Comment by pwrmiller** [comment]
Resolved in v1.2.0!
