### ISSUE TITLE
Cannot use `max_user_history_length_percentile` and `min_user_history_length_percentile` in serviceConfig for aws-user-personalization recipe

### ISSUE THREAD

**Issue by GroovyDan** [aws-solutions/maintaining-personalized-experiences-with-machine-learning#15]
**Describe the bug**
When you use `max_user_history_length_percentile` and `min_user_history_length_percentile` instead of `max_hist_length_percentile` and `min_hist_length_percentile` for feature transformation parameters, you will get a mismatch error after solution is created when it goes to check the status. I believe this is due to the fact that Personalize changes the parameters names under the hood, and when the solution calls the api to get the current configuration, the parameter names are different and no longer align with the ones you specified in your config file.

**To Reproduce**
Update load a configuration file with a service configuration similar to the following:
`
{
      "serviceConfig": {
        "name": "test-solution",
        "recipeArn": "arn:aws:personalize:::recipe/aws-user-personalization",
        "solutionConfig": {
          "algorithmHyperParameters": {
              "bptt": "32",
              "hidden_dimension": "149",
              "recency_mask": "true"
          },
          "featureTransformationParameters": {
              "max_user_history_length_percentile": "1.0",
	      "min_user_history_length_percentile": "0.00"
          }
        }
      }
`

**Expected behavior**
I would expect this solution to be able to handle both sets of
 parameter names, `max_user_history_length_percentile` and `min_user_history_length_percentile` as well as `max_hist_length_percentile` and `min_hist_length_percentile`.

**Please complete the following information about the solution:**
- [x] Version: [e.g. v0.0.1]
1.2.0

To get the version of the solution, you can look at the description of the created CloudFormation stack. For example, "(SO0170) Maintaining Personalized Experiences with Machine Learning [...]".

- [x] Region: [e.g. us-east-1]
us-east-1
- [x] Was the solution modified from the version published on this repository?
no
- [ ] If the answer to the previous question was yes, are the changes available on GitHub?
- [x] Have you checked your [service quotas](https://docs.aws.amazon.com/general/latest/gr/aws_service_limits.html) for the sevices this solution uses?
yes
- [ ] Were there any errors in the CloudWatch Logs?

**Screenshots**
If applicable, add screenshots to help explain your problem (please **DO NOT include sensitive information**).
<img width="811" alt="Screen Shot 2022-04-08 at 10 52 41 AM" src="https://user-images.githubusercontent.com/44237509/162478158-a26d8b2f-d902-47e7-9154-25c7f026703c.png">

**Additional context**

**Comment by GroovyDan** [comment]
Now it appears you can no longer use the deprecated `max_hist_length_percentile` and `min_hist_length_percentile` at all, but if you try to use `max_user_history_length_percentile` and `min_user_history_length_percentile`, you still get the above mentioned error since the describe call still return the deprecated names.

**Comment by tabdunabi** [comment]
Hi @GroovyDan thank you for reporting the issue.  We will work on revamping the solution, and release a new version as soon as possible.

**Comment by supreetkt** [comment]
Hi @GroovyDan, @a6patch - the root cause of this issue was found to be the underlying Personalize API response, which was using deprecated field names. A fix went in on Jan 3rd and we have verified that when the `serviceConfig` is supplied with `max_user_history_length_percentile` and `min_user_history_length_percentile` parameters, the solution gets created with these, as expected.
