### ISSUE TITLE
Publish events to EventBridge at each stage of a Personalize workflow

### ISSUE THREAD

**Issue by james-jory** [aws-solutions/maintaining-personalized-experiences-with-machine-learning#2]
**Is your feature request related to a problem? Please describe.**
To make this solution more integration-friendly with infrastructure deployed around Personalize, it would be beneficial to be able to setup rules and targets in EventBridge to react to workflow stages as they complete using code.

**Describe the feature you'd like**
As the workflow completes various stages (i.e., dataset import complete, solution version complete, campaign create/update complete, batch inference job complete), fire an event with details on the resource and outcome to EventBridge. Customers could then build listeners for these events to update state in their application code around Personalize. For example, suppose a customer is using a blue/green deployment model with Personalize where they switch between blue and green dataset groups each week, being able to listen to a campaign create/update completion event would allow them to switch their middleware to call the new campaign and tear down the campaign in the other DSG to reduce cost.

**Comment by pwrmiller** [comment]
Hi James - this is a great idea. There are some complexities in introducing this functionality into the workflow, but I'll consider what can be done to introduce this functionality, since it would be so useful.

**Comment by pwrmiller** [comment]
Resolved in v1.10!
